package org.pgpb.spreadsheet;

import com.google.common.collect.ImmutableList;

import java.util.Arrays;
import java.util.List;

import static java.util.stream.Collectors.toList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Spreadsheet {
    private List<CellRow> rows;

    public Spreadsheet(ImmutableList<String> tsvRows) {
        this.rows = tsvRows.stream()
            .map(tsvRow -> convertToCells(tsvRow))
            .map(CellRow::new)
            .collect(toList());
    }

    private List<Cell> convertToCells(String tsvRow) {
        String[] tsvCells = tsvRow.split("\\t");
        List<Cell> cells = Arrays.asList(tsvCells)
            .stream()
            .map(Cell::new)
            .collect(toList());
        return cells;
    }

    public boolean someLibraryMethod() {
        return true;
    }

    public List<String> toTSVRows() {
        return rows.stream()
            .map(cellRow -> cellRow.toString())
            .collect(toList());
    }
}
