package org.pgpb.spreadsheet;

import com.google.common.collect.ImmutableList;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.IntStream;

import static java.util.stream.Collectors.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Spreadsheet {
    private static final Logger LOGGER = LoggerFactory.getLogger(Spreadsheet.class);
    private Dimensions dimensions;
    private Cell[][] cells;

    public Spreadsheet(int rows, int columns) {
        cells = new Cell[rows][];
        for (int r = 0; r < rows; r++) {
            cells[r] = new Cell[columns];
        }
    }

    private static Dimensions parseHeader(String[] header) {
        int rowCount = Integer.parseInt(header[0]);
        int columnCount = Integer.parseInt(header[1]);

        if (rowCount < 0 || columnCount < 0) {
            throw new RuntimeException("Invalid headers");
        }

        return new Dimensions(rowCount, columnCount);
    }

    public static Spreadsheet fromTsvLines(List<String> lines) {
        String[] header = lines.get(0).split("\\t");
        Dimensions dimensions = parseHeader(header);

        Cell [][] cells = lines.stream()
            .skip(1)
            .map(l -> l.split("\\t"))
            .map(Arrays::asList)
            .map(entries -> entries.stream()
                .map(Cell::new)
                .toArray(Cell[]::new))
            .toArray(Cell[][]::new);

        Spreadsheet spreadsheet = new Spreadsheet(dimensions.rows, dimensions.columns);
        spreadsheet.setCells(cells);
        return spreadsheet;
    }

    public int getRowCount() {
        return cells.length;
    }

    public int getColumnCount() {
        return cells[0].length;
    }

    public Cell getCell(String address) {
        Coordinate coordinate = Coordinate.fromAddress(address) ;
        return cells[coordinate.row][coordinate.column];
    }
    public void setCells(Cell[][] cells) {
        this.cells = cells;
    }

    public ImmutableList<String> toTSVLines() {
        ImmutableList lines = Arrays.asList(cells).stream()
            .map(Arrays::asList)
            .map(cellRow -> cellRow.stream()
                .map(Cell::getContent)
                .collect(joining("\t"))
            ).collect(ImmutableList.toImmutableList());
        return lines;
    }

    public ImmutableList<Cell[]> getRows() {
        return ImmutableList.copyOf(Arrays.asList(cells));
    }

    private static class Dimensions {
        public final int rows;
        public final int columns;

        public Dimensions(int rowCount, int columnCount) {
            rows = rowCount;
            columns = columnCount;
        }
    }
}
